Repository petl-developers/petl, pull requests merged in 2022-02, with the labels that each got.

#593 cd: publish releases to PyPI with GA
  .github/workflows/publish-release.yml
Labels: Maintainability, Build CI CD

#525 prettier github start page with drawing
  README.rst
  docs/index.rst
  docs/petl-architecture.png
Labels: Documentation

#599 Align docs changes with Github releases
  docs/changes.rst
Labels: Documentation

#604 github: added a conda forge release status badge
  README.rst
Labels: Maintainability, Build CI CD

#603 vscode: enabe code analysis
  .vscode/settings.json
Labels: Maintainability

#609 pytest: test tohtml with css styles
  petl/test/io/test_html.py
Labels: Maintainability

#612 Add missing v1.7.8 entries in changes.rst
  docs/changes.rst
Labels: Documentation

#613 Fix iterrowslice to conform with Python 3.7 PEP 479 which transforms …
  docs/changes.rst
  petl/test/transform/test_basics.py
  petl/transform/basics.py
Labels: Usability
